
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fazal
 */
public class Farmer_Home extends javax.swing.JFrame {
    Connection conn;
    Timer timer;
    //Calculating the sec
    public static int Sec = 60;
    public static ImageIcon imgData;
    
    /**
     * Creates new form Farmer_Home
     */
    public Farmer_Home() {
        initComponents();
        dbConn();
        tabledata();
        
    }
    public void dbConn(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/auction", "root", "roott");
          //  System.out.println("Driver LOad successfully");
        } catch (Exception e) {
           // System.out.println("Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_faddItem = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_fStartAuction = new javax.swing.JButton();
        btn_imgSelect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_fAddedProducts = new javax.swing.JTable();
        txt_ownerName = new javax.swing.JTextField();
        txt_itemName = new javax.swing.JTextField();
        txt_resPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_imagePath = new javax.swing.JTextField();
        txt_quantity = new javax.swing.JTextField();
        lbl_displayImg = new javax.swing.JLabel();
        lbl_timer = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Auction AGRI");

        jLabel2.setText("Item Name : ");

        jLabel3.setText("Owner Name : ");

        jLabel4.setText("Reserverd Price : ");

        btn_faddItem.setText("ADD ITEM");
        btn_faddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_faddItemActionPerformed(evt);
            }
        });

        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_fStartAuction.setText("START AUCTION");
        btn_fStartAuction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fStartAuctionActionPerformed(evt);
            }
        });

        btn_imgSelect.setText("SELECT IMAGE");
        btn_imgSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imgSelectActionPerformed(evt);
            }
        });

        tbl_fAddedProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Item Image", "Owner Name", "Item Name", "Quantity", "Reserverd Price", "Winner Name", "Sold Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_fAddedProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_fAddedProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_fAddedProducts);

        txt_ownerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ownerNameActionPerformed(evt);
            }
        });

        txt_itemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_itemNameActionPerformed(evt);
            }
        });

        txt_resPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_resPriceActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel6.setText("TIMER : ");

        jLabel7.setText("Quantity : ");

        txt_imagePath.setEnabled(false);
        txt_imagePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_imagePathActionPerformed(evt);
            }
        });

        txt_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantityActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btn_faddItem))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_resPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_quantity, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_itemName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_displayImg, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(44, 44, 44)
                                    .addComponent(txt_ownerName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(btn_imgSelect)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(txt_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_fStartAuction)
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_timer)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(lbl_timer))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_ownerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_resPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_imgSelect)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(txt_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_displayImg, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btn_faddItem)
                    .addComponent(btn_fStartAuction))
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ownerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ownerNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_ownerNameActionPerformed

    private void txt_itemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_itemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_itemNameActionPerformed

    private void txt_resPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_resPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_resPriceActionPerformed

    private void btn_imgSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imgSelectActionPerformed
        // TODO add your handling code here:
        //pop-up a window with all files in the pc
        JFileChooser fileChooser = new JFileChooser();
        //Choose only "png", "jpg", "jpeg"
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        fileChooser.addChoosableFileFilter(fnef);
        int openDialog = fileChooser.showOpenDialog(null);
        if(openDialog == fileChooser.APPROVE_OPTION){
            //Save the selected File in this variable
            File selectedFile = fileChooser.getSelectedFile();
            String selectedImgPath = selectedFile.getAbsolutePath();
            //Setting the path of the selected item
            txt_imagePath.setText(selectedImgPath);
            
            //Displaying Image
            ImageIcon Ii = new ImageIcon(selectedImgPath);
            //Resizing to fit the label
            Image img = Ii.getImage().getScaledInstance(lbl_displayImg.getWidth(), lbl_displayImg.getHeight(), Image.SCALE_SMOOTH);
            lbl_displayImg.setIcon(new ImageIcon(img));
        }
        
    }//GEN-LAST:event_btn_imgSelectActionPerformed

    private void txt_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantityActionPerformed

    private void txt_imagePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_imagePathActionPerformed
        // TODO add your handling code here:
       txt_imagePath.setVisible(false);
    }//GEN-LAST:event_txt_imagePathActionPerformed

    private void btn_faddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_faddItemActionPerformed
        // TODO add your handling code here:
        //Show error msg Field Required
        if(txt_ownerName.getText().equals("")||txt_itemName.getText().equals("")||txt_quantity.getText().equals("")||txt_resPrice.getText().equals("")||txt_imagePath.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please Fill All The Fields to Add your Item", "Required Filed", 2);
        }else{
            //Get the typing datas to the variable        
        String ownerName = txt_ownerName.getText();
        String itemName = txt_itemName.getText();
        String quantity = txt_quantity.getText();
        String resPrice = txt_resPrice.getText();
        //Getting the img path to set in File Obj
        String imgPath = txt_imagePath.getText();
        
        
        try {
            //Creating a File Obj to find the img path
            File f = new File(imgPath);
            //Created the iS to read the imgPath and store the img in "iS" variable
            InputStream iS = new FileInputStream(f);
            Statement stmt = conn.createStatement();
            String insertQ = ("INSERT INTO faddProduct(OwnerName, ItemName, Quantity, ReservedPrice,Image) VALUES ('"+ownerName+"', '"+itemName+"', '"+quantity+"', '"+resPrice+"', '"+iS+"') ");
            stmt.execute(insertQ);
            stmt.close();
           
            
            txt_ownerName.setText("");
            txt_itemName.setText("");
            txt_quantity.setText("");
            txt_resPrice.setText("");
            txt_imagePath.setText("");
        
            
            JOptionPane.showMessageDialog(null, "Item Addedd successfully", "Add Item", 1);
            
        } catch (SQLException ex) {
            Logger.getLogger(Farmer_Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Farmer_Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Farmer_Home.class.getName()).log(Level.SEVERE, null, ex);
        }
             tabledata();
        }
        
        
       
        
        
        
        
    }//GEN-LAST:event_btn_faddItemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Main_Login().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_fStartAuctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fStartAuctionActionPerformed
        // TODO add your handling code here:
        
        String oName = txt_ownerName.getText();
        String iName = txt_itemName.getText();
        String quan = txt_quantity.getText();
        String resPrice = txt_resPrice.getText();
       // String imgPath = txt_imagePath.getText();
        
        
        try {
           // File f = new File(imgPath);
            //InputStream iS =new FileInputStream(f);
            Statement stmt = conn.createStatement();
            String insertQ = "INSERT INTO Auctioned_Item values( '"+oName+"', '"+iName+"', '"+quan+"', '"+resPrice+"' )";
            stmt.execute(insertQ);
            stmt.close();
            JOptionPane.showMessageDialog(null, "Your Auction Has Started", "Auction Started", 1);
            
        } catch (SQLException ex) {
            Logger.getLogger(Farmer_Home.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
        startTimer();
        timer.start();
        
        txt_ownerName.setText("");
        txt_itemName.setText("");
        txt_quantity.setText("");
        txt_resPrice.setText("");
    }//GEN-LAST:event_btn_fStartAuctionActionPerformed

    private void tbl_fAddedProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_fAddedProductsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel) tbl_fAddedProducts.getModel();
        int row = tbl_fAddedProducts.getSelectedRow();
        
        //Getting the values from the selected row
        //Blob img = (Blob) tm.getValueAt(row, 0);
        
        //byte[] img = (byte[]) tm.getValueAt(row, 0);
        //ImageIcon imageIcon = new ImageIcon(img);
        //Image im = imageIcon.getImage();
        //Image newImg = im.getScaledInstance(lbl_displayImg.getWidth(), lbl_displayImg.getHeight(), Image.SCALE_SMOOTH);
        //mageIcon finalImg = new ImageIcon(newImg);
        //imgData = finalImg;
        
        String oName = (String) tm.getValueAt(row, 2);
        String iName = (String) tm.getValueAt(row, 3);
        String quan = (String) tm.getValueAt(row, 4);
        String resPrice = (String) tm.getValueAt(row, 5);
        
        
        //Setting the value to the particlar field
        txt_ownerName.setText(oName);
        txt_itemName.setText(iName);
        txt_quantity.setText(quan);
        txt_resPrice.setText(resPrice);
        
       // lbl_displayImg.setIcon(imgData);
        
        
        
    }//GEN-LAST:event_tbl_fAddedProductsMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txt_ownerName.setText("");
        txt_itemName.setText("");
        txt_quantity.setText("");
        txt_resPrice.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    public void startTimer(){
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Sec--;
                if(Sec==-1){
                    timer.stop();
                    //want to adf the tabledata()
                }
                else if(Sec>=0&&Sec<10)lbl_timer.setText("00:0"+Sec);
                else lbl_timer.setText("00:"+Sec);
            }
        });
    }
    
    public void tabledata(){
         //Retreving data from db = faddProduct
        DefaultTableModel tm = (DefaultTableModel) tbl_fAddedProducts.getModel();
        
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * from faddProduct  "/*Id, Image, OwnerName, ItemNAME, Quantity, ReservedPrice*//*ORDER BY ID DESC LIMIT 1*/);
            
            while(rs.next()){
                int id = rs.getInt("Id");
                Blob img = rs.getBlob("Image");
                String oName = rs.getString("OwnerName");
                String iName = rs.getString("ItemName");
                String quan = rs.getString("Quantity");
                String rPrice = rs.getString("ReservedPrice");
                String wName = rs.getString("Winner_Name");
                int sPrice = rs.getInt("SoldPrice");
                
                tm.addRow(new Object[]{ id,img,oName, iName, quan, rPrice, wName, sPrice });
               
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Farmer_Home.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Farmer_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Farmer_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Farmer_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Farmer_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Farmer_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_fStartAuction;
    private javax.swing.JButton btn_faddItem;
    private javax.swing.JButton btn_imgSelect;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_displayImg;
    private javax.swing.JLabel lbl_timer;
    private javax.swing.JTable tbl_fAddedProducts;
    private javax.swing.JTextField txt_imagePath;
    private javax.swing.JTextField txt_itemName;
    private javax.swing.JTextField txt_ownerName;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_resPrice;
    // End of variables declaration//GEN-END:variables
}
